- bin/htest.js
- src/js/node-run.js
The cli will now exit with a non-zero exit code if one or more tests fail.
> Non-zero exit code when there are test failures

- src/env/node.js
- src/util.js
Fixes #26 
- Intercept the console before running the tests and restore it after all the tests are finished.
- We can replay all the intercepted messages later if needed. Do we need a separate option for this?
> Don't mess up the CLI output with `console.log`s (`console.warn`s, etc) from tests

- src/env/node.js
If it doesn't, passed tests will never be rendered, even in the `verbose` mode.
This is a cherry-pick from #31.
> [Interactive CLI] `render` should consider all passed options, not only `format`

- src/classes/TestResult.js
- src/env/node.js
- src/util.js
In this PR, I tried to implement [@LeaVerou's suggestion on handling console messages from tests](https://github.com/LeaVerou/htest/issues/7#issuecomment-2141051134), including (as an addition to the main algorithm):
- Refactor `interceptConsole()` so that it accepts a function as an argument
- Add utility `pluralize()` method to correctly print out “message”/“messages” to the console
Here is what we have as a starting point:
https://github.com/LeaVerou/htest/assets/9166277/61478182-77c6-4832-a0f8-8924d09deef9
Let's improve it and make it more awesome together!
> First stab at handling console messages while a test runs

- src/env/node.js
Closes #37.
In this PR, I switched from the `Alt` key to `Ctrl` by addressing Lea's feedback and based on my experiments (there are issues when detecting `Alt` since it's interpreted as a meta key; I thought that meta corresponds to `⌘` on Mac and `Ctrl` on Windows 🤷‍♂️).
Anyhow, here is the list of supported keyboard shortcuts:
- `↑` — “Go Level Up” (current behavior)
- `↓` — “Go Level Down” (current behavior)
- `→` — “Expand Node” (current behavior)
- `←` — “Collapse Node” (current behavior)
- `Ctrl+↑` — “Go to the First Child of a Group”
- `Ctrl+↓` — “Go to the Last Child of a Group”
- `Ctrl+→` — “Expand Subtree” (starting from the current node) — the same as “Expand All” when performed on root
- `Ctrl+←` — “Collapse Subtree” (starting from the current node) — the same as “Collapse …
> Keyboard shortcuts

- src/env/node.js
Fixes the issue with `ERR_UNSUPPORTED_ESM_URL_SCHEME` on Windows ([reported](https://github.com/color-js/color.js/pull/616#issue-2747672182) in the Color.js repo). Now, `hTest` should work in all major OSs.
We still have some UI glitches because our emojis are not well-supported in different Windows terminals. But I think we can work on it in a different PR.
> [node.js] Support running tests in Node in all OSs

- package-lock.json
- package.json
- src/classes/TestResult.js
- src/util.js
Changes:
- Add support for inline (current) and vertical formatting of the test results
- Highlight (per character, including whitespace) the difference between actual and expected values
- Unmapped values are dimmed out
> First stub at improving failure display, closes #52

- README.md
- docs/run/node/README.md
- src/cli.js
- src/env/node.js
- src/run.js
via the `--ci` flag
The diff in `src/env/node.js` is a bit messy, but I only added the check for the CI mode and moved the old code to the `else` branch.
When some of the tests fail, we exit with code `1` and output some additional info that looks like this:
> Add basic support for non-interactive mode

- src/classes/TestResult.js
- src/env/auto.js
- src/util.js
- Move `IS_NODEJS` to `util`
- Make the `diff` package available both in Node.js and the browser
After adding the `diff` package to improve the fail screen, we broke the HTML mode (see the [Color.js testsuite](https://colorjs.io/test/) as an example): it fails with the `Uncaught (in promise) TypeError: Failed to resolve module specifier "diff". Relative references must start with either "/", "./", or "../"` error. This PR fixes it.
> Fix the HTML mode

- src/classes/Test.js
- src/classes/TestResult.js
I still need to add some docs, but I want to ensure I get the idea right.
My local experiments with another project show that those inheritable methods work.
@LeaVerou, I'd love to hear your thoughts on this.
> First stab at adding support for `setup()` and `teardown()`

- src/html/harness.js
Number of passed and failed tests are in the `content` property of the `::before` pseudo element, not in `textContent`, so the totals are not updated. Since we already have the `--pass` and `--fail` custom properties on `<body>`, we can use them to update the totals.
> Fix totals in the HTML mode

- docs/define/README.md
- src/classes/Test.js
- src/classes/TestResult.js
- Rename: `setup` → `beforeEach`, `teardown` → `afterEach`
- Add support for `beforeAll` and `afterAll` (not inheritable)
- Simplify the code: no need for dummy functions; simply envoke them if they are defined
- Add some docs
> Another iteration on setup and teardown

- src/html/util.js
When `args` is an object containing nested objects, we have the following output in the HTML mode (mind commas at the beginning and end of the string):
With this PR, the output is fixed:
> [HTML mode] Improve rendering of nested objects

- src/util.js
Otherwise, when running JS-first tests in the browser, we lose all the console messages produced by the tests.
> Don't intercept console when not in Node

- src/classes/TestResult.js
- Maintain proper sequencing when hooks (`beforeEach`/`afterEach`, `beforeAll`/`afterAll`) are used
- Fall back to parallel execution (using `Promise.all`) when no hooks exist
Now, we might end up (I already was bit by this bug) calling `afterAll` before `afterEach` for some tests. In most cases, `beforeEach` for all tests is called before the first test runs. There are probably some more issues we haven't encountered yet. This PR should fix those bugs.
> Fix bugs with setup and teardown

- htest.css
- src/html/harness.js
- src/html/reftest.js
- src/html/testpage.js
- src/render.js
- Rename class `ignore` to `skipped` to be even with the JS mode
Here is how it looks:
> [HTML] Add support for skipped tests

- htest.css
- src/html/testpage.js
- Add some margin to make the scrolled-into-view test fully visible
- Consider as a test not only direct children of `tbody` but also direct children of the reftest table itself (the exact case when we render JS-first tests)
- Generate unique ids (sometimes, tests might have the same name, so we can't simply use them as ids). Without unique ids, the isolation feature doesn't work as expected
> [HTML mode] Make test isolation and the navigation between individual tests work again

- htest.css
- src/render.js
Otherwise, there is no way to understand why error- and time-based tests fail.
With the change, a message in the console also shows diff:
> [HTML] On click, show details for failing tests in the console

- src/classes/TestResult.js
- src/cli.js
- src/env/node.js
For now, even if we specify that option, groups with all passed tests won’t be shown. In CI/CD, this option is not respected even partially. Rel to #7 and #96.
With the changes, one can enable verbose output via the `--verbose` CLI argument.
I also changed the formatting of skipped tests. For now, they are formatted as failed. Unfortunately, we don’t have many ANSI colors to choose from, so I decided to stick with yellow (I also tried black, as it was the closest to gray, but I thought the final look wasn't decent enough).
As a result of all these changes, we can get (when testing `color.js`):
Running tests with both options (`ci` and `verbose`) enabled allows us to (at least partially) address use cases mentioned by @kleinfreund in #96.
> Respect the `verbose` option when printing out results

- src/classes/TestResult.js
Fixes the issue when logging objects. For now, we get `[object Object]` in such cases. [Found](https://github.com/htest-dev/htest/issues/96#issuecomment-2984253506) by @kleinfreund.
> Stringify intercepted messages before printing them out
